manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/algeboard
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: test
      import: app/west.yml
  self:
    path: config
